
aws.region=${AWS_REGION}
aws.accessKeyId=${AWS_ACCESS_KEY_ID}
aws.secretAccessKey=${AWS_SECRET_ACCESS_KEY}

#aws.dynamodb.table.message=chat_message
#aws.dynamodb.table.room=chat_room
aws.dynamodb.table.message=${DYNAMODB_TABLE_MESSAGE}
aws.dynamodb.table.room=${DYNAMODB_TABLE_ROOM}
aws.dynamodb.table.user=${DYNAMODB_TABLE_USER}

server.port=8080
spring.application.name=websocket-chat